---
- hosts: tank
  become: true
  tasks:
    - name: Get ammo
      synchronize:
        src=load/ammofile.txt
        dest=/home/vvsushkov/ammofile.txt
    - name: Get token
      synchronize:
        src=load/token.txt
        dest=/home/vvsushkov/token.txt
#    - name: Setup conf
#      template:
#        src=load/load_get.yaml.tpl
#        dest=/home/vvsushkov/load.yaml
#    - name: Run test
#      docker_container:
#        image: direvius/yandex-tank
#        name: tank
#        state: started
#        auto_remove: true
#        pull: true
#        volumes:
#          - /home/vvsushkov:/var/loadtest
#          - /home/vvsushkov/.ssh:/root/.ssh
    - name: Setup conf
      template:
        src=load/load_post.yaml.tpl
        dest=/home/vvsushkov/load.yaml
    - name: Run test
      docker_container:
        image: direvius/yandex-tank
        name: tank
        state: started
        auto_remove: true
        pull: true
        volumes:
          - /home/vvsushkov:/var/loadtest
          - /home/vvsushkov/.ssh:/root/.ssh
