apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-volume-claim
  containers:
  - name: postgres
    image: postgres
    env:
      - name: POSTGRES_PASSWORD
        value: password
    ports:
      - containerPort: 5432
    volumeMounts:
      - mountPath: "/var/lib/postgresql/data"
        name: postgres-volume
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 6432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres