apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: cr.yandex/crp913jl8n7be2qhb7r4/todo:amd64
          imagePullPolicy: Always
          env:
            - name: DATABASE_URI
              value: postgresql://postgres:password@:1/postgres
            - name: DATABASE_HOSTS
              value: $(POSTGRES_SERVICE_HOST)
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007